import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { Raleway } from "next/font/google";

const alegreya = Raleway({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`px-24 flex flex-col justify-between h-screen bg-[#E9E7DF]  ${alegreya.className}`}
      >
        <link
          rel="icon"
          href="https://em-content.zobj.net/source/apple/354/world-map_1f5fa-fe0f.png"
          sizes="any"
        />
        {children}
      </body>
    </html>
  );
}
